services:
  localstack:
    image: localstack/localstack:3.0.2
    ports:
      - '4567:4566' # Remap LocalStack Gateway to different host port
      - '4610-4659:4510-4559' # Remap service port range
    env_file:
      - 'compose/aws.env'
    environment:
      DEBUG: ${DEBUG:-1}
      LS_LOG: WARN # Localstack DEBUG Level
      SERVICES: s3,sqs,sns,firehose
      LOCALSTACK_HOST: 127.0.0.1
    volumes:
      - '${TMPDIR:-/tmp}/localstack:/var/lib/localstack'
      - ./compose/start-localstack.sh:/etc/localstack/init/ready.d/start-localstack.sh
    healthcheck:
      test: ['CMD', 'curl', 'localhost:4566']
      interval: 5s
      start_period: 5s
      retries: 3
    networks:
      - cdp-tenant

  redis:
    image: redis:7.2.3-alpine3.18
    ports:
      - '6380:6379' # Remap Redis to a non-default host port
    restart: always
    networks:
      - cdp-tenant

  mongodb:
    image: mongo:6.0.13
    networks:
      - cdp-tenant
    ports:
      - '27017:27017'
    volumes:
      - mongodb-data:/data
    restart: always


  apha-apps-perms-case-mgmt-api:
    build:
      context: .
      target: development
    ports:
      - '3001:3001'
    links:
      - 'localstack:localstack'
      - 'mongodb:mongodb'
    depends_on:
      localstack:
        condition: service_healthy
      mongodb:
        condition: service_started
    env_file:
      - 'compose/aws.env'
    environment:
      PORT: 3001
      NODE_ENV: development
      SQS_ENDPOINT: http://localstack:4566
      MONGO_URI: mongodb://mongodb:27017/
      SHAREPOINT_TB25_TENANT_ID: ${SHAREPOINT_TB25_TENANT_ID}
      SHAREPOINT_TB25_CLIENT_ID: ${SHAREPOINT_TB25_CLIENT_ID}
      SHAREPOINT_TB25_CLIENT_SECRET: ${SHAREPOINT_TB25_CLIENT_SECRET}
      SHAREPOINT_TB25_SITE_ID: ${SHAREPOINT_TB25_SITE_ID}
      SHAREPOINT_TB25_LIST_ID: ${SHAREPOINT_TB25_LIST_ID}
      SHAREPOINT_TB25_DRIVE_ID: ${SHAREPOINT_TB25_DRIVE_ID}
      SHAREPOINT_TB25_FOLDER_PATH: ${SHAREPOINT_TB25_FOLDER_PATH}
      NOTIFY_API_KEY: ${NOTIFY_API_KEY}

      TB_NOTIFY_CASE_DELIVERY_EMAIL_ADDRESS: ${TB_NOTIFY_CASE_DELIVERY_EMAIL_ADDRESS}
      TB_NOTIFY_APPLICANT_CONFIRMATION_TEMPLATE_ID: ${TB_NOTIFY_APPLICANT_CONFIRMATION_TEMPLATE_ID}
      TB_NOTIFY_CASE_DELIVERY_TEMPLATE_ID: ${TB_NOTIFY_CASE_DELIVERY_TEMPLATE_ID}

      EXOTICS_NOTIFY_CASE_DELIVERY_EMAIL_ADDRESS: ${EXOTICS_NOTIFY_CASE_DELIVERY_EMAIL_ADDRESS}
      EXOTICS_NOTIFY_APPLICANT_CONFIRMATION_TEMPLATE_ID: ${EXOTICS_NOTIFY_APPLICANT_CONFIRMATION_TEMPLATE_ID}
      EXOTICS_NOTIFY_CASE_DELIVERY_TEMPLATE_ID: ${EXOTICS_NOTIFY_CASE_DELIVERY_TEMPLATE_ID}
    networks:
      - cdp-tenant
    volumes:
      - ./src:/home/node/src
      - ./package.json:/home/node/package.json

################################################################################

volumes:
  mongodb-data:

networks:
  cdp-tenant:
    driver: bridge
    name: cdp-tenant
